### ISSUE TITLE
Incorrect input keyboard layout.

### ISSUE THREAD

**Issue by xaizone** [WootingKb/wooting-macros#105]
Hey,
I was trying to use Wootomation for the first time and ran into an issue while setting up a trigger key for my macro. 
The app ignores any user defined keyboard layout inside of Windows and uses the English (US) layout instead, which makes it very confusing for some users that are not familiar with the English layout.
I have double-checked in both Windows and in the Wootility software and I got the Czech layout present in both, yet the Wootomation app uses the English layout.
I also tried changing the keyboard layout to something else (Russian & French), both with the same outcome.

Steps to reproduce:
1. Change your Windows keyboard layout to anything other than English (US).
2. Set your new trigger key using the selected keyboard layout.
3. Wootomation uses the English layout instead of the user-defined one.

LMK if you need further information.

**Comment by medzernik** [comment]
Does this happen when you change the layout first and then start the macro app? Does it still use an inappropriate layout?

**Comment by xaizone** [comment]
Yes, correct. I've restarted Wootomation after each keyboard layout change and the issue still persists.
Could the locale of my Windows cause the issue? Since I'm running English (US) localization, but use the [Czech](https://learn.microsoft.com/en-us/globalization/keyboards/kbdcz) keyboard layout.

**Comment by medzernik** [comment]
Well this is a bit more complicated -- you basically define which keys need to be pressed and which do get pressed. the triggers are keys - whether it's a 2 or ě or ľ, those keys need to be pressed. Currently its by a key, not by position. Changing this would require rethinking the entire analysis approach, but I guess could be done later. Or maybe some other clever trick
