### ISSUE TITLE
Portable Windows Installation

### ISSUE THREAD

**Issue by denis-roy** [WootingKb/wooting-macros#121]
# WHAT
Include a portable Windows installation

# WHY
- To be able to use Wootomation on a computer where the user is a non-admin account (for example on a company-provided laptop)
- Because the current MSI requires admin rights even if installing to a user-owned folder

# HOW

- Make Wootomation Windows registry independant (Might already be? Have not checked)
    - Write registry keys/config in a file instead (could be inspired by [PortableApps dev format](https://portableapps.com/development/portableapps.com_format))
- Provide a .zip that contains all files and dependencies, that can simply be uncompressed to user-owned folder and run without requiring admin rights

**Comment by medzernik** [comment]
I think this issue goes into more depth:
https://github.com/tauri-apps/tauri-action/issues/59

Basically, there should be a flag we can set to not require admin rights, but Tauri is still very much in development. Have you tried the 1.1 yet? I updated the libraries there, maybe the installer behaves differently now.

Either way the MSI is kinda required for the webview2 part. Unfortunately, distributing the EXE file standalone could mean you can't run the app as you don't have the prerequisites installed. However, feel free to try and take the wootomation.exe and just use that as the portable version. Though, it may not work everywhere.

**Comment by denis-roy** [comment]
Thank you for your reply!

I have not tried 1.1, the highest version I see in the release section is v1.0.1 which is the one I've udpated to a few days ago. The MSI still asked for admin priviledges when I tried to install to a user-owned folder.

I confirm that copying `Wootomation.exe` from a PC on which it is installed and running it on a machine on which it was not installed worked for me.

I also confirm that extracting the MSI using [7-zip](https://7-zip.org/) and renaming the resulting `Path` file to `Wootomation.exe` also worked for me so until Tauri reaches v1.3 and non-admin installer are a thing, that's what I'll do to keep up to date on the non-admin machine.

Thank you!

**Comment by denis-roy** [comment]
I was thinking that if Webview2 is the only prerequisite, distributing the .EXE along with their [evergreen bootstrapper](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) (or a README.txt with a link to download it) could be a more graceful way than what I described above though :)
