### ISSUE TITLE
F13-F24 not recognized as trigger keys

### ISSUE THREAD

**Issue by ssvx** [WootingKb/wooting-macros#135]
Title says it all. Not sure about other less common keys, but i tried F13 to F24 as trigger keys and they are just not recognized.

My setup is a Wooting Two HE where i've mapped Fn+F1 as F13, Fn+F2 as F14, etc ... and Fn+F12 as F24. In addition i've set F13 as action for the scroll wheel press on my Swiftpoint Z.

Expected result: Wootomation should register F13...F24 when recording trigger keys.
Current result: Neither using the 2HE nor using the Z to send F13...F24 is being recorded as Wootomation trigger key.

Would be awesome if you could look into it and add these! <3

Notice/btw: the F13...F24 keys _do_ work when recording the actual macro sequence - just not as trigger keys. Tho for some reason there's a weird behaviour with F13 which always only registers as "key up", not as "full press". F14 to F24 on the other hand correctly record as "full press" in a macro sequence consistently.

**Comment by ssvx** [comment]
Regarding the notice / post scriptum:
Since it was F13 that i had also mapped to my mouse i went ahead and changed it to F14 on the mouse. This however doesn't affect the recorded sequence - the "full press" of F13 still registers as "key up" and F14 on the mouse is recorded correctly. Hence i dare say the mouse mapping is unrelated to this quirk =)

**Comment by medzernik** [comment]
is the FN key by any chance interpreted somewhat differently by the OS? cant think why they wouldnt work elsewise

**Comment by ssvx** [comment]
Not sure - i thought maybe Fn might not be processed by the OS at all and just serves to shift internal mapping layers on keyboard-side?

Tho i already had F13 on my mouse (and therefore thought it's independent of Fn) i just tried to set F14 on the A key of the 2HE and tested again. To my surprise this worked. Next i tested Fn+F1...F12 again. What can i say: F14 (Fn+F2) to F24 (Fn+F12) now work perfectly fine!

Now i feel stupid.. 👀

Almost wanted to close the issue, but F13 still doesn't work. Tho that's **the one** that only registers as "key up" and never as "full press" - maybe not even a wootomation issue, but a problem with wootility and the 2HE not sending "key down"?

Not sure where to go from here.

**Comment by ssvx** [comment]
Err. It's getting crazier. Bear with me...

I just re-mapped Fn+F1 as F13 again, thought maybe that could solve something. Then i went to wootility-lekker advanced keys and used the "Test your bindings" field to check if F13-F24 work properly. Result: F14-F24 do work properly. F13 doesn't register.

But (and this is the slightly crazy part) pressing Fn+F1 (F13) makes my mouse jump randomly. Mostly just ~15 pixels in a random direction, but sometimes what feels like 200 pixels. Super weird.

Observing this i don't think it's an issue with wootomation and would like to apologize for any confusion i may have caused. But what else could it be? Where should i take the issue? Could someone map Fn+F1 as F13 and try it in the "Test your bindings" thingy in wootility-lekker?

If you like, please feel free to close this issue - then i'll ask other users on Discord to confirm this. If all 2HE (and maybe 60HE or even the Two) behave the same i think i should take the issue to wootility project..

**Comment by sIRwa2** [comment]
im using touchportal to execute the F13 and upwards keys. seems to work fine on my end.
