### ISSUE TITLE
Have never been able to get macros working

### ISSUE THREAD

**Issue by joewang704** [WootingKb/wooting-macros#167]
I've created fairly simple macros. Input is either a key or CTRL + a key and then output should be spaces/any key pressed multiple times. This has never worked.

**Comment by medzernik** [comment]
Duplicate of #105

**Comment by medzernik** [comment]
> I've created fairly simple macros. Input is either a key or CTRL + a key and then output should be spaces/any key pressed multiple times. This has never worked.

Might be related to #171

**Comment by medzernik** [comment]
Can you please try 1.1 and see if you still have the issue? @joewang704
