### ISSUE TITLE
[Feature] Adding Randomization Delays on keystrokes or delays

### ISSUE THREAD

**Issue by YvesChasse** [WootingKb/wooting-macros#202]
It would be a nice feature to add the ability to allow people to add delays with randomization wich will trigger or delay for a randomized period of set time (ms to ms). You never know when you might want to have this, but none the less it's nice to have just incase with it being in a decent amount of macros these days.

**Comment by medzernik** [comment]
The only idea that comes to mind this could be used for is to bypass anticheats in certain games. Do you have another usecase this could be useful for?

**Comment by medzernik** [comment]
Cannot add due to it being able to partially circumvent some anticheat software (or flag the user for actual cheating)

**Comment by clearlyqt** [comment]
Ive been thinking about buying a wooting keyboard but it's hard to give up this feature which is standard in Corsairs ICUE and has been for as long as i can remember, example pic showing the option on delays in ICUE
![image](https://github.com/user-attachments/assets/6fa7c435-baeb-48b1-a61d-08c7133ef3a4)

edit: better image, not sure if anyone will even see this as its closed, i dont use github, but didnt wanna make a new thread when theres a topic on it already
