### ISSUE TITLE
Add function Keys as modifiers

### ISSUE THREAD

**Issue by Lywelle** [WootingKb/wooting-macros#217]
On the wooting 60HE there is not that much space tu place macros effectively.

Using the Function layer and function layer 2 to place Macros would be a great addition.

Due to the characteristics of the FUnction key this would be a difficult project.

**Comment by simon-wh** [comment]
You should try using the F13-F24 bindings in Wootility. You can bind those to your Fn layer and then use those as triggers for macros. It's a bit limited, i.e. 12 bindings, but it should allow you to do what you're looking for
