### ISSUE TITLE
System events not working

### ISSUE THREAD

**Issue by raphaelcarnassale** [WootingKb/wooting-macros#220]
On windows 11 most of the "System Events" macros seems to be broken.
Already tried running as Administrator but no success.

Events that did not work:
1)Open website
2)Open file
3)Open folder
4)Increase volume
5)Decrease volume

Sacrastify and paste text worked fine.

**Comment by medzernik** [comment]
just tested on release, works fine for me. Do you have any special software running by any chance? What is the trigger you use?

**Comment by raphaelcarnassale** [comment]
Just re-tested everything and realized the System Events do not work when I trigger them with Wootomation window open and focused. 
Not sure if a bug or a intentional, but this caused me and my friend confusion thus concluding System events did not work.

**Comment by medzernik** [comment]
It's intentional (being able to control the application) and ability to test a macro using a button will be added in 1.2 or later. However, this behavior may also change with new releases.
