### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by simon-wh** [WootingKb/wooting-macros#40]
- [ ] Write README.md
    - [ ] Feature overview
    - [ ] maybe one or two screenshots
    - [ ] Download / Install instructions
    - [ ] Credits
- [ ] Write COMPILING.md with details on what dependencies are required to build the project and dev commands and instructions
    - Examples
        - https://github.com/WootingKb/wooting-analog-midi#development-setup
        - https://github.com/WootingKb/wooting-double-movement#contributing
- [ ] A md doc (e.g. ADDING_INTEGRATIONS.md) which goes over the steps required to add an additional Integration/Plugin
- [ ] Define repo topics & description

**Comment by medzernik** [comment]
Closed by #45
