### ISSUE TITLE
Certain numpad keys & combinations do not work as trigger keys

### ISSUE THREAD

**Issue by khanguyen7** [WootingKb/wooting-macros#87]
### Issue(s)
**The following keys alone do not work as intended as trigger keys**
- Numpad Decimal (but pressing the regular period key triggers the macro instead)
- Numpad Enter

**The following key combinations do not work as intended as trigger keys (seems like they are also captured by the other application). These ones I'm not sure if they can be resolved.**
- CTRL + Numpad Add, num lock (when focused on a browser or text file, it zooms in)
- CTRL + Numpad 1-9, subtract, divide, multiply (outputs paste text action twice with a 'v' in between)
- CTRL + any regular number key (outputs paste text action twice with a 'v' in between)
- ALT + any numpad key (generates symbols)
- ALT + any regular number key
- SHIFT + numpad 1-9, numpad decimal, numpad enter

### Confirmed Variables
- Windows Environment (Linux not tested)

### Possible Workaround
- Remap numpad keys to F13-24 in an Fn layer (only really affects full size boards)

There are potentially more unintended behaviours.

**Comment by BigBrainAFK** [comment]
Shift + Numpad is a Windows OS level modifier that makes it use the non NumLock functions instead like Numpad End etc. Unsure if that is something we can really fix.

**Comment by medzernik** [comment]
I'll look into this soon, but am very suprised because i tried a lot of these combinations and they always worked. Maybe its keyboard layouts? Interesting.

**Comment by khanguyen7** [comment]
It may just be an issue for the paste text action, as a user would have to be focused on an input field in an application to use it.

**Comment by medzernik** [comment]
Fixed the numpad decimal/regular period, it will be available in #80

**Comment by medzernik** [comment]
> Shift + Numpad is a Windows OS level modifier that makes it use the non NumLock functions instead like Numpad End etc. Unsure if that is something we can really fix.

We won't be able to fix this probably, OS handles the key first as its detected.
