### ISSUE TITLE
Add unicode support

### ISSUE THREAD

**Issue by Huhni** [WootingKb/wooting-macros#92]
Please add support for more than just the regular keyboard keys. For example in AHK you can do 
```
RAlt & n::
  Send {U+00F1}
return
```
to send the letter `ñ`

**Comment by medzernik** [comment]
> Please add support for more than just the regular keyboard keys. For example in AHK you can do
> 
> ```
> RAlt & n::
>   Send {U+00F1}
> return
> ```
> 
> to send the letter `ñ`

You should be able to do it via the Paste Text action. Alternatively, we could add a special action, but i don't think it would be that much different implementation wise to the paste text one.
